# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  image-name:  vplauzon/wordpress2jekyll
  docker-registry-endpoint:  'vplauzon-docker-hub'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: dotnet test **/*test -c release
      displayName: 'Test'
    - script: dotnet publish wordpress2jekyll -c release -o app
      displayName: 'Build / Publish wordpress2jekyll'
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: 'wordpress2jekyll/Dockerfile'
        imageName: '$(image-name):$(tag)'
    - task: Docker@2
      displayName: 'Push Docker image'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: '$(docker-registry-endpoint)'
        command: 'Push an image'
        imageName: '$(image-name):$(tag)'
